### ISSUE TITLE
Nord tmux doesn't look as intended

### ISSUE THREAD

**Issue by ArjunSahlot** [arcticicestudio/nord-tmux#69]
I am running `gnome-terminal` on ubuntu with 24bit true color enabled. 
![proof](https://user-images.githubusercontent.com/44180430/159096973-f51f4392-ea02-42b6-8026-995c3c5cfc81.png)

I have also added this line to my `.tmux.conf` file: `set-option -ga terminal-overrides ",xterm-256color:Tc"`

Nord tmux still doesn't look as intended:
![proof](https://user-images.githubusercontent.com/44180430/159097081-465336c8-2abc-4e07-a5d4-09a27975e830.png)

What should I do to make it look correct?

**Comment by m-parchami** [comment]
To all other newbies who're just like me looking for the solution to this, you have to install Powerline fonts so that you have the required fonts (that includes nice arrows and stuff). Checkout [here](https://github.com/powerline/fonts). (and don't forget to open a new terminal for testing).

I'm still trying to fix the color thing. But fixing the font should give you something like this:
![Screenshot from 2022-11-28 13-39-34](https://user-images.githubusercontent.com/56980571/204279993-1a6070a0-5906-414f-8511-335504cbc458.png)

**Comment by m-parchami** [comment]
To all other newbies who're just like me looking for the solution to this, you have to install Powerline fonts so that you have the required fonts (that includes nice arrows and stuff). Checkout [here](https://github.com/powerline/fonts). (and don't forget to open a new terminal for testing).

![Screenshot from 2022-11-28 13-39-34](https://user-images.githubusercontent.com/56980571/204279993-1a6070a0-5906-414f-8511-335504cbc458.png)


And for the color, go [here](https://github.com/arcticicestudio/nord-gnome-terminal), install the nord theme. Now go to your terminal preferences and on the left you should see Nord. Click on the arrow and set it as default :)
![Screenshot from 2022-11-28 13-47-36](https://user-images.githubusercontent.com/56980571/204281622-e24f9081-75eb-421e-8777-e396ec5a5ebf.png)
![Screenshot from 2022-11-28 13-48-33](https://user-images.githubusercontent.com/56980571/204281746-88de360b-d35f-4b32-8b92-49208614850b.png)

**Comment by brumik** [comment]
@m-parchami I would like to ask if there is a solution to the non-pixel-perfectness of the patched version "arrows". I have it working perfectly on Mac, but on my gnome linux Alacritty (same config) it is a bit "off" that bothers me a little. 

![image](https://github.com/nordtheme/tmux/assets/8531681/f6f64b91-298f-419d-b437-f5cb95e1f473)


![image](https://github.com/nordtheme/tmux/assets/8531681/44d4ff58-6182-47fb-af6b-5604631d0a2d)


I do not even understand what can cause it and what to google, but I see that many people have it in their screenshots (but it seems that it is resolvable by some)

**Comment by cstromquist** [comment]
Any solutions to this @brumik ? I am having the same issues with the arrows.

**Comment by brumik** [comment]
I could not even figure out the cause, so unfortunately not, and this issue was not worth more than a few hours of research for me. If you figure it out please let me know.

**Comment by brumik** [comment]
@cstromquist I think I figured it out. This is an issue with my font Alacritty setup. I had:
```yml

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  # Point size
  size: 14.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 1
    y: 1
```

where turns out the offset messes up "design" characters. If you set
```yml
  offset:
    x: 0
    y: 0
```

It looks good.
